spring.application.name=simpleAuth

# Encoding e Charset
spring.mandatory-file-encoding=UTF-8

# Configurações do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/simpleAuth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URL Base do Front-End
# Definimos o valor padrão aqui. Quando o NgrokConfig rodar, ele vai sobrescrever via System.setProperty
app.frontend.url=https://couples-pens-picnic-villas.trycloudflare.com

# Bot Central (Hub)
telegram.bot.hub.token=8887156896:AAHcp2ro9o-x1oIxXsLYdpnCSOExmXadCg4
telegram.bot.hub.username=ConnectHubSpoke_bot

# Bots Secundários
telegram.bot.med.token=8959129809:AAFs6BH6ihUMHNBxgvIv2fcALhn80TdhcKg
telegram.bot.med.username=NotificaMedBot

telegram.bot.evento.token=8299920925:AAE2LV0SDjT9AgZtXXfS26QFs-a4ffCH0ww
telegram.bot.evento.username=NotificaEventoBot

telegram.bot.compra.token=8846691934:AAEh6uYVCvjlzsqKNlZFIJ2UtF6CAHAQyPQ
telegram.bot.compra.username=NotificaCompraBot

# Garante que o cookie de sessão funcione nas chamadas CORS
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=false