spring.application.name=simpleAuth

# Encoding e Charset
spring.mandatory-file-encoding=UTF-8

# Configuracoes do Banco de Dados (Le as variaveis de ambiente do Render com fallback local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/connecthub-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Configuracoes do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL Base do Front-End (Vercel)
app.frontend.url=${APP_FRONTEND_URL:https://connecthub-frontend-three.vercel.app}

# Bot Central (Hub)
telegram.bot.hub.token=8887156896:AAHcp2ro9o-x1oIxXsLYdpnCSOExmXadCg4
telegram.bot.hub.username=ConnectHubSpoke_bot

# Bots Secundarios
telegram.bot.med.token=8959129809:AAFs6BH6ihUMHNBxgvIv2fcALhn80TdhcKg
telegram.bot.med.username=NotificaMedBot

telegram.bot.evento.token=8299920925:AAE2LV0SDjT9AgZtXXfS26QFs-a4ffCH0ww
telegram.bot.evento.username=NotificaEventoBot

telegram.bot.compra.token=8846691934:AAEh6uYVCvjlzsqKNlZFIJ2UtF6CAHAQyPQ
telegram.bot.compra.username=NotificaCompraBot

# Garante que o cookie de sessao funcione nas chamadas CORS
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true